name: 'Sparse checkout'
description: 'Sparse checkout a git repository'
inputs:
  # same as actions/checkout
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
# TODO: implement
#   ssh-key:
#     description: >
#       SSH key used to fetch the repository. The SSH key is configured with the local
#       git config, which enables your scripts to run authenticated git commands.
#       The post-job step removes the SSH key.


#       We recommend using a service account with the least permissions necessary.


#       [Learn more about creating and using
#       encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
#   ssh-known-hosts:
#     description: >
#       Known hosts in addition to the user and global host key database. The public
#       SSH keys for a host may be obtained using the utility `ssh-keyscan`. For example,
#       `ssh-keyscan github.com`. The public key for github.com is always implicitly added.
#   ssh-strict:
#     description: >
#       Whether to perform strict host key checking. When true, adds the options `StrictHostKeyChecking=yes`
#       and `CheckHostIP=no` to the SSH command line. Use the input `ssh-known-hosts` to
#       configure additional hosts.
#     default: true
#   persist-credentials:
#     description: 'Whether to configure the token or SSH key with the local git config'
#     default: true
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: .
# TODO: implement
#   clean:
#     description: 'Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching'
#     default: true
#   fetch-depth:
#     description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
#     default: 1
#   lfs:
#     description: 'Whether to download Git-LFS files'
#     default: false
#   submodules:
#     description: >
#       Whether to checkout submodules: `true` to checkout submodules or `recursive` to
#       recursively checkout submodules.


#       When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are
#       converted to HTTPS.
#     default: false

  # sparse checkout
  patterns:
    description: >
      Write a set of patterns to the sparse-checkout file.
      
      [Learn more about set](https://git-scm.com/docs/git-sparse-checkout#Documentation/git-sparse-checkout.txt-emsetem)
    default: '*'
    required: true

runs:
  using: composite
  steps:
    - name: Getting Git version info
      run: |
        set -x
        /usr/bin/git version
      shell: bash
    - name: Cloning the repository
      run: |
        set -x
        echo $REF
        if [ -n "$REF" ]; then
          BRANCH=$REF
        else
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
        fi
        echo $BRANCH
        /usr/bin/git clone --no-checkout --filter=tree:0 --depth 1 --branch $BRANCH $REPOSITORY $PATH
      env:
        PATH: ${{ inputs.path }}
        REPOSITORY: https://${{ github.actor }}:${{ inputs.token }}@github.com/${{ inputs.repository }}.git
        REF: ${{ inputs.ref }}
      shell: bash
#     - name: Make directory
#       run: |
#         set -x
#         /usr/bin/mkdir -p $PATH
#       env:
#         PATH: ${{ inputs.path }}
#       shell: bash
#     - name: Initializing the repository
#       run: |
#         set -x
#         /usr/bin/git init
#         /usr/bin/git remote add origin $REPOSITORY
#         /usr/bin/git config --local http.https://github.com/.extraheader "AUTHORIZATION: token $TOKEN"
#       env:
#         REPOSITORY: https://${{ github.actor }}:${{ inputs.token }}@github.com/${{ inputs.repository }}.git
#         TOKEN: ${{ inputs.token }}
#       shell: bash
    - name: Disabling automatic garbage collection
      run: |
        set -x
        /usr/bin/git config --local gc.auto 0
      shell: bash
    - name: Sparse checkout
      run: |
        set -x
        /usr/bin/git sparse-checkout init --cone
        /usr/bin/git sparse-checkout set $PATTERNS
      env:
        PATTERNS: ${{ inputs.patterns }}
      working-directory: ${{ inputs.path }}
      shell: bash
#     - name: Fetching the repository
#       run: |
#         set -x
#         BRANCH="${GITHUB_REF/#refs\/heads\//}" # TODO: inputs.ref
#         /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
#       working-directory: ${{ inputs.path }}
#       shell: bash
    - name: Checking out the ref
      run: |
        set -x
        echo $REF
        if [ -n "$REF" ]; then
          BRANCH=$REF
        else
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
        fi
        echo $BRANCH
        /usr/bin/git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      env:
        REF: ${{ inputs.ref }}
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: |
        set -x
        /usr/bin/git log -1 --format='%H'
      shell: bash
