name: 'Sparse checkout'
description: 'Sparse checkout a git repository'
inputs:
  # Same as actions/checkout
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: .

  # sparse checkout
  patterns:
    description: >
      Write a set of patterns to the sparse-checkout file.

      [Learn more about set](https://git-scm.com/docs/git-sparse-checkout#Documentation/git-sparse-checkout.txt-emsetem)
    default: '*'
    required: true

runs:
  using: composite
  steps:
#     - name: Cloning the repository
#       run: /usr/bin/git clone --no-checkout --filter=tree:0 --depth 1 $REPOSITORY $PATH
#       env:
#         PATH: ${{ inputs.path }}
#         REPOSITORY: https://${{ github.actor }}:${{ inputs.token }}@github.com/${{ inputs.repository }}.git
#       shell: bash

    - run: gh api rate_limit
      shell: bash

    - run: echo "::group::Getting Git version info"
      shell: bash
    - name: Getting Git version info
      run: /usr/bin/git version
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Preparing the repository"
      shell: bash
    - run: |
        set -x
        pwd
        echo $GITHUB_SERVER_URL
        if [ -d $PATH ]; then
          # already exists
          cd $PATH
          /usr/bin/git config --local --get remote.origin.url
          /usr/bin/git branch -a
        else
          # first clone
          /usr/bin/mkdir -p $PATH
          cd $PATH
          /usr/bin/git init
          /usr/bin/git remote add origin ${GITHUB_SERVER_URL}/${REPOSITORY}
        fi
      env:
        REPOSITORY: ${{ inputs.repository }}
        PATH: ${{ inputs.path }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

#     - name: Make directory
#       run: /usr/bin/mkdir -p $PATH
#       env:
#         PATH: ${{ inputs.path }}
#       shell: bash

#     - run: echo "::group::Initializing the repository"
#       shell: bash
#     - run: /usr/bin/git init
#       working-directory: ${{ inputs.path }}
#       shell: bash
#     - run: /usr/bin/git remote add origin $REPOSITORY
#       env:
#         REPOSITORY: ${{ env.GITHUB_SERVER_URL }}/${{ inputs.repository }}
#       working-directory: ${{ inputs.path }}
#       shell: bash
#     - run: /usr/bin/git remote -v
#       working-directory: ${{ inputs.path }}
#       shell: bash
#     - run: echo "::endgroup::"
#       shell: bash

    - run: echo "::group::Disabling automatic garbage collection"
      shell: bash
    - run: /usr/bin/git config --local gc.auto 0
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Setting up auth"
      shell: bash
    - run: |
        BASIC_CREDENTIAL="x-access-token:$(echo $TOKEN | xxd -p -c 256)"
        echo "::add-mask::${BASIC_CREDENTIAL}"
        /usr/bin/git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ${BASIC_CREDENTIAL}"
      env:
        TOKEN: ${{ inputs.token }}
      shell: bash
    - name: debug
      run: |
        /usr/bin/git config --local http.https://github.com/.extraheader
        cat .git/config
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Setting up sparse checkout"
      shell: bash
    - name: Sparse checkout
      run: |
        cat .git/config
        /usr/bin/git sparse-checkout init --cone
        /usr/bin/git sparse-checkout set $PATTERNS
      env:
        PATTERNS: ${{ inputs.patterns }}
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Determining the default branch"
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Fetching the repository"
      shell: bash
    - name: Fetching the repository
      run: |
        echo $REF
        if [ -z "$REF" ]; then
          if [ "$REPOSITORY" == "$GITHUB_REPOSITORY" ]; then
            REF="${GITHUB_REF/#refs\/heads\//}"
          else
            REF=$(gh api repos/$REPOSITORY --jq '.default_branch')
          fi
        fi
        echo $REF
        /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${REF}:refs/remotes/origin/${REF}
      env:
        REF: ${{ inputs.ref }}
        REPOSITORY: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Checking out the ref"
      shell: bash
    - name: Checking out the ref
      run: |
        # FIXME: duplication with fetch
        echo $REF
        if [ -z "$REF" ]; then
          if [ "$REPOSITORY" == "$GITHUB_REPOSITORY" ]; then
            REF="${GITHUB_REF/#refs\/heads\//}"
          else
            REF=$(gh api repos/$REPOSITORY --jq '.default_branch')
          fi
        fi
        echo $REF
        /usr/bin/git checkout --progress --force -B $REF refs/remotes/origin/$REF
      env:
        REF: ${{ inputs.ref }}
        REPOSITORY: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
      working-directory: ${{ inputs.path }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: /usr/bin/git log -1 --format='%H'
      shell: bash
