name: Approve

on:
  pull_request:
    types: [ review_requested ]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.actor }}
      - run: gh pr review --approve
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        if: ${{ github.actor == 'SnowCait' }}
