name: Approve

on:
  pull_request:
    types: [ review_requested ]

jobs:
  approve:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    if: ${{ github.event.requested_reviewer.login == 'SnowCait-Test1' }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
      - run: gh pr review --approve $NUMBER
        env:
          GH_TOKEN: ${{ github.token }}
          NUMBER: ${{ github.event.number }}
      - run: gh pr edit $NUMBER --remove-reviewer $REVIEWER
        env:
          NUMBER: ${{ github.event.number }}
          REVIEWER: ${{ github.event.requested_reviewer.login }}
