name: Branch

on:
  pull_request:
#     types: [ opened ]
#     branches:
#       - feature/**
#       - fix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $GITHUB_REF
      - run: echo ${{ github.event.head.ref }}
