name: Checkout config
on:
  push:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "チェックアウト"
      - run: git config --local -l
      - name: set git config
        env:
          READONLY_GITHUB_TOKEN: ${{ secrets.READONLY_GITHUB_TOKEN }}
        run: git config --global url."https://${READONLY_GITHUB_TOKEN}:x-oauth-basic@github.com/SnowCait".insteadOf "https://github.com/SnowCait"
      - name: access remote
        # gitでリモートアクセスするサンプル
        run: git clone https://github.com/SnowCait/private-repository.git
