name: Default branch

on:
  push:
    paths:
      - .github/workflows/default-branch.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.repository.default_branch }}
