name: Default branch

on:
  push:
    paths:
      - .github/workflows/default-branch.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.repository.default_branch }}
      - uses: actions/checkout@v2
        with:
          repository: SnowCait/rest-api-description
      - run: git branch
