name: EditorConfig

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
#     - uses: docker://greut/eclint
#     - uses: zbeekman/EditorConfig-Action@v1.1.1
#       env:
#         ALWAYS_LINT_ALL_FILES: true
    - run: ls -la
    - run: pwd
    - run: ls -la ../
    - run: ls -la ../../
    - run: ls -la ../../_PipelineMapping/SnowCait/
    - run: ls -la ../../_actions/snow-actions/
    - run: ls -la ../../_actions/snow-actions/eclint/
    - run: ls -la ../../_actions/snow-actions/eclint/v1.0.0/
    - run: ls -la /
    - run: echo $HOME
    - run: echo $GITHUB_WORKSPACE
    - uses: snow-actions/eclint@feature/add-matrix-test
      with:
        args: '--version'
#     - uses: snow-actions/eclint@v1.0.0
#       with:
#         args: 'check'

