name: EditorConfig

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: zbeekman/EditorConfig-Action@v1.1.1
      env:
        ALWAYS_LINT_ALL_FILES: true
    - uses: snow-actions/eclint@feature/add-matrix-test
      with:
        args: '--version'
    - uses: snow-actions/eclint@feature/add-matrix-test
      with:
        args: 'check'

