name: EditorConfig

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: zbeekman/EditorConfig-Action@v1.1.1
      env:
        ALWAYS_LINT_ALL_FILES: true
    - uses: snow-actions/eclint@v1.0.0
      with:
        args: '--version'

