name: GitHub CLI

on:
  push:
    paths: .github/workflows/gh.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GitHub CLI
      run: |
        curl -fsSL -O https://github.com/github/homebrew-gh/releases/download/v0.5.0/gh_0.5.0_linux_amd64.deb
        sudo dpkg -i gh_*_linux_amd64.deb
    - run: gh help
