name: GitHub CLI

on:
  push:
    paths:
      - .github/workflows/gh.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - name: Install GitHub CLI
#       run: |
#         curl -fsSL -O https://github.com/github/homebrew-gh/releases/download/v0.5.0/gh_0.5.0_linux_amd64.deb
#         sudo dpkg -i gh_*_linux_amd64.deb
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GH_REPO
      env:
        GH_REPO: ${{ github.repository }}
    - run: echo $GH_REPO
      env:
        GH_REPO: ${{ GITHUB_REPOSITORY }}
    - run: gh --version
    - run: gh --help
    - run: gh repo list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh pr list --repo SnowCait/actions-sandbox
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh pr list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: SnowCait/actions-sandbox
    - run: ls -la
#     - uses: actions/checkout@v2
    - run: gh repo clone SnowCait/actions-sandbox . -- --depth 1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: ls -la
    - run: gh pr list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
