name: GitHub CLI

on:
  push:
    paths:
      - .github/workflows/gh.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
#     - name: Install GitHub CLI
#       run: |
#         curl -fsSL -O https://github.com/github/homebrew-gh/releases/download/v0.5.0/gh_0.5.0_linux_amd64.deb
#         sudo dpkg -i gh_*_linux_amd64.deb
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GH_REPO
      env:
        GH_REPO: ${{ github.repository }}
    - run: gh --version
    - run: gh --help
    - run: gh repo list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh pr list --repo $GITHUB_REPOSITORY
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh pr list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}

    # ヘルプ
    - run: gh actions --help

    # ワークフロー
    - run: gh workflow list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}

    # ワークフロー実行ログ
    - run: gh run list --workflow 'GitHub CLI'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
    - run: gh run list --workflow gh.yml
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}

    # 実行中のワークフロー（無限ループするので要タイムアウト）
    - run: gh run watch $(gh run list --workflow gh.yml --limit 1 | cut -f 7)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      timeout-minutes: 1

    - run: ls -la
#     - uses: actions/checkout@v2
    - run: gh repo clone $GITHUB_REPOSITORY . -- --depth 1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: ls -la
    - run: ls -la .github/
    - run: gh pr list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
