name: GitHub Container registory

on:
  push:
    paths:
      - .github/workflows/ghcr.yml
      - ghcr/**/*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ghcr/

    steps:
      - uses: actions/checkout@v2
      - run: docker build -t github-runner .
      - run: docker images
      - run: docker images --quiet
      - run: docker tag $(docker images --quiet) ghcr.io/SnowCait/github-runner:latest
