name: Git Commands

on:
  schedule:
    - cron: '* * * * *'
  push:
    paths: .github/workflows/git.yml

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/git-commands
    - uses: dawidd6/action-git-user-config@v1.0.0
    - run: mkdir -p files
    - run: echo 'content' >> files/file.txt
#     - name: git config
#       run: |
#         git config user.email email@example.com
#         git config user.name example
    - run: git add -A
    - run: git commit -m 'try commit'
    - run: git push
