name: Git Commands

on:
  push:
    paths: .github/workflows/git.yml

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/git-commands
    - run: mkdir -p files
    - run: echo 'content' >> files/file.txt
    - name: git
      run: |
        git config user.email email@example.com
        git config user.name example
        git add -A
    - run: git commit -m 'try commit'
    - run: git push
