name: Git Commands

on:
  push:
    paths: .github/workflows/git.yml

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir -p files
    - run: echo 'content' >> files/file.txt
    - name: git
      run: |
        git config user.email email@example.com
        git config user.name example
        git checkout -b feature/git-commands
        git add -A
        git commit -m 'try commit'
    - uses: actions/checkout@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: feature/git-commands
