name: Git Commands

on:
  push:
    paths: .github/workflows/git.yml

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir -p files
    - run: echo 'content' >> files/file.txt
    - name: git
      run: |
        git checkout -b feature/git-commands
        git commit -a -m 'try commit'
        git push origin feature/git-commands
