name: Git Commands

on:
  workflow_dispatch:
#   schedule:
#     - cron: '* * * * *'
  push:
    paths: .github/workflows/git.yml

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/git-commands
    - name: git config の代替
      uses: dawidd6/action-git-user-config@v1.0.0
#     - name: git config
#       run: |
#         git config user.email email@example.com
#         git config user.name example
    - run: mkdir -p files
    - run: echo 'content' >> files/file.txt
    - run: git add -A
    - run: git commit -m 'try commit'
    - run: git push
