name: github-script

on: [issues]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/github-script@v3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({...context.issue, body: '👋 Thanks for reporting!'})
