name: Issue

on: [issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: cat $GITHUB_EVENT_PATH
    - run: echo ${{ github.event.comment.body }}
    - run: echo LGTM is contained
      if: contains(github.event.comment.body, 'LGTM')
