name: Issue

on: [issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: cat $GITHUB_EVENT_PATH
    - uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.pulls.createReviewRequest({owner: 'SnowCait', repo: 'action-sandbox', pull_number: ${{ github.event.issue.number }}, event: 'APPROVE'})
      if: contains(github.event.comment.body, 'LGTM') && github.event.issue.pull_request
