name: Outputs

on:
  push:
    paths: .github/workflows/outputs.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Read a file
      id: readfile
      run: echo '::set-output name=text::'; cat ./github/workflows/outputs.yml
    - name: Output
      run: echo ${{ steps.readfile.outputs.text }}
