name: Outputs

on:
  push:
    paths: .github/workflows/outputs.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#     - name: Read a file
#       id: readfile
#       run: TEXT=$(<.github/workflows/outputs.yml)";
    - name: Output
      run: echo ${TEXT}
      env:
        TEXT: test
