name: Protected branch (client)

on:
  push:
    paths:
      - client/**
      - .github/workflows/protected-branch-client.yml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./client/test.sh
