name: Pull Request Review

on: [pull_request_review]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - run: cat $GITHUB_EVENT_PATH
    - run: echo ${{ github.event.action }}
    - name: Reviews
      id: reviews
      uses: octokit/request-action@v2.0.2
      with:
        route: GET /repos/${{ github.repository }}/pulls/{${{ fromJSON(github.event).pull_request.number }}/reviews
    - run: "echo ${{ steps.reviews.outputs.data }}"
