name: Pull Request
on:
  pull_request:
    paths: .github/workflows/pull_request.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_WORKSPACE
      - run: cat $GITHUB_EVENT_PATH
      - run: git version
      - uses: actions/checkout@v2
      - run: git status
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git status
