name: Pull Request Trigger Sandbox
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_EVENT_NAME
      - run: echo $GITHUB_EVENT_PATH
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $GITHUB_WORKSPACE
      - run: GITHUB_WORKSPACE=${GITHUB_WORKSPACE}/Packer
      - run: echo $GITHUB_WORKSPACE
      - uses: docker://hashicorp/packer:1.4.3
        with:
          args: validate packer2.json
