name: sample
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: HELLO
        run: echo 'hello, action'
      - name: test
        uses: ./
