name: Pusher

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.ref }},${{ github.event.pusher.name }}" >> pusher.csv
      - run: git add pusher.csv
      - run: git commit -m "pusher.csv"
      - run: git push    
