name: sample
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: HELLO
      #   run: echo 'hello, action'
      # - name: nodejs
      #   uses: ./nodejs-action/
      # - name: php
      #   uses: ./docker-action/
      # - name: packer
      #   uses: ./packer-action/
      - uses: docker://hashicorp/packer
        with:
          args: validate packer.json
      - uses: docker://hashicorp/packer
        with:
          args: validate invalid.json
