name: QRCode PR
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo ${{ toJson(github.event.pull_request) }}
#     - uses: actions/checkout@v2
#       with:
#         ref: qrcode
#     - uses: SnowCait/qrcode@v1.0.0
#       with:
#         text: ${{ github. }}
#         path: qrcode.png
