name: QRCode
on:
  push:
    paths:
      - .github/workflows/qrcode.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: SnowCait/qrcode@master
      with:
        text: 'sample'
        path: 'sample.png'
