name: QRCode
on:
  push:
    paths:
      - .github/workflows/qrcode.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git checkout -b qrcode
    - uses: SnowCait/qrcode@master
      with:
        text: ${{ github.run_id }}
        path: 'sample.png'
    - run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add sample.png
        git commit -m "sample.png"
        git push origin qrcode
