name: Released

on:
  workflow_dispatch:
  release:
    type: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ toJson(github.event) }}
      - uses: snow-actions/tweet@v1.0.0
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: Released
