name: Skip CI

on:
  push:
    paths:
      - .github/workflows/skip.yml
  pull_request:
    paths:
      - .github/workflows/skip.yml

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.body, '[skip ci]') }}

    steps:
      - run: 'echo hello'
      - run: 'echo world'
