name: Sparse checkout

on:
  push:
    paths:
      - .github/workflows/sparse-checkout.yml
      - .github/sparse-checkout/action.yml
  workflow_dispatch:

jobs:
  local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout .github/sparse-checkout/
        uses: actions/checkout@v2.3.4

      - name: 1st
        uses: ./.github/sparse-checkout/
        with:
          patterns: 'docs packer'
          path: sparse
      - run: ls -l sparse/

#       - name: 2nd
#         uses: ./.github/sparse-checkout/
#         with:
#           patterns: 'docs packer'
#           path: sparse
#       - run: ls -l sparse/

      - name: sha
        uses: ./.github/sparse-checkout/
        with:
          patterns: 'docs packer'
          path: sha
          ref: 1068da213d7ecfae787d21630bc0955e31a6659a
      - run: ls -l sparse/

      - name: other repo
        uses: ./.github/sparse-checkout/
        with:
          repository: snow-actions/tweet
          patterns: 'src'
          path: tweet
          # ref: main
      - run: ls -l sparse/

  gogaille:
    runs-on: ubuntu-latest

    steps:
      - name: 1st
        uses: gogaille/sparse-checkout@v0
        with:
          patterns: 'docs packer'
      - run: ls -l

      - name: 2nd
        uses: gogaille/sparse-checkout@v0
        with:
          patterns: 'docs packer'
      - run: ls -l

  checkout:
    runs-on: ubuntu-latest

    steps:
#       - name: 1st
#         uses: actions/checkout@v2.3.4
#       - run: ls -l

#       - name: 2nd
#         uses: actions/checkout@v2.3.4
#       - run: ls -l

      - name: other repo
        uses: actions/checkout@v2.3.4
        with:
          repository: snow-actions/tweet
      - run: ls -l
      - run: git config http.https://github.com/.extraheader
      - run: cat .git/config
