name: Sparse checkout

on:
  push:
    paths:
      - .github/workflows/sparse-checkout.yml
      - .github/sparse-checkout/
  workflow_dispatch:

jobs:
  local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/sparse-checkout/
        with:
          patterns: 'docs packer'
          path: sparse
      - run: ls -l sparse/

  gogaille:
    runs-on: ubuntu-latest

    steps:
      - uses: gogaille/sparse-checkout@v0
        with:
          patterns: 'docs packer'
      - run: ls -l
