name: Sparse checkout

on:
  push:
    paths:
      - .github/workflows/sparse-checkout.yml
      - .github/sparse-checkout/action.yml
  workflow_dispatch:

jobs:
  local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout .github/sparse-checkout/
        uses: actions/checkout@v2.3.4

      - name: 1st
        uses: ./.github/sparse-checkout/
        with:
          patterns: 'docs packer'
          path: twice
      - run: ls -l twice/

      - name: 2nd
        uses: ./.github/sparse-checkout/
        with:
          patterns: 'docs packer'
          path: twice
      - run: ls -l twice/

      - name: sha
        uses: ./.github/sparse-checkout/
        with:
          patterns: 'docs packer'
          path: sha
          ref: 1068da213d7ecfae787d21630bc0955e31a6659a
      - run: ls -l sha/

      - name: other repo
        uses: ./.github/sparse-checkout/
        with:
          repository: snow-actions/tweet
          patterns: 'src'
          path: other
          # ref: main
      - run: ls -l other/

      - name: private
        uses: ./.github/sparse-checkout/
        with:
          repository: SnowCait/github-actions-self-hosted-runner-sandbox
          path: private
      - run: ls -l private/

  gogaille:
    runs-on: ubuntu-latest

    steps:
      - name: 1st
        uses: gogaille/sparse-checkout@v0
        with:
          patterns: 'docs packer'
      - run: ls -l

# fatal: destination path '.' already exists and is not an empty directory.
#       - name: 2nd
#         uses: gogaille/sparse-checkout@v0
#         with:
#           patterns: 'docs packer'
#       - run: ls -l

  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: 1st
        uses: actions/checkout@v2.3.4
        with:
          path: twice
      - run: ls -l twice/

      - name: 2nd
        uses: actions/checkout@v2.3.4
        with:
          path: twice
      - run: ls -l twice/

      - name: other repo
        uses: actions/checkout@v2.3.4
        with:
          repository: snow-actions/tweet
          path: other
      - run: ls -l other/
      - run: git config http.https://github.com/.extraheader
        working-directory: other
      - run: cat .git/config
        working-directory: other

      - name: private
        uses: actions/checkout@v2.3.4
        with:
          repository: SnowCait/github-actions-self-hosted-runner-sandbox
          path: private
      - run: ls -l private/

