name: Status Trigger

on:
  status:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_EVENT_NAME
      - run: cat $GITHUB_EVENT_PATH
      - run: echo '${{ toJson(github.event.branches) }}'
      - run: |
          echo ${{ join(github.event.branches.*.name, ', ') }}
          echo '::set-output name=names::${{ github.event.branches.*.name }}'
        id: branches
      - run: echo ${{ steps.branches.outputs.names }}
