name: Status Trigger

on:
  status:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_EVENT_NAME
      - run: cat $GITHUB_EVENT_PATH
      - run: echo '${{ toJson(github.event.branches) }}'
      - run: |
          echo ${{ join(github.event.branches.*.name, ', ') }}
          echo '::set-output name=names::${{ join(github.event.branches.*.name) }}'
        id: branches
      - run: echo ${{ steps.branches.outputs.names }}
      
      # state が success なら commit 全体の state を見に行く
      - name: GET /repos/{owner}/{repo}/commits/{sha}/status
        uses: octokit/request-action@v2.0.2
        id: commit_state
        with:
          route: GET /repos/{owner}/{repo}/commits/{sha}/status
          owner: SnowCait
          repo: action-sandbox
          sha: ${{ github.event.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.state == 'success'
      - run: echo '${{ steps.commit_state.outputs.data }}'
        if: github.event.state == 'success' && steps.commit_state.outputs.status == 200
      - run: |
          echo 'state: ${{ fromJson(steps.commit_state.outputs.data).state }}'
        if: github.event.state == 'success' && steps.commit_state.outputs.status == 200
      
      # コミットが含まれる PR を見に行く
      - name: GET /repos/{owner}/{repo}/commits/{sha}/pulls
        uses: octokit/request-action@v2.0.2
        id: pulls
        with:
          route: GET /repos/{owner}/{repo}/commits/{sha}/pulls
          owner: SnowCait
          repo: action-sandbox
          sha: ${{ github.event.sha }}
          mediaType: |
            previews:
              - groot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.state == 'success'
      - run: echo '${{ steps.pulls.outputs.data }}'
        if: github.event.state == 'success' && steps.pulls.outputs.status == 200
      - run: |
          echo 'state: ${{ toJson(fromJson(steps.pulls.outputs.data).*.state) }}'
          echo 'draft: ${{ toJson(fromJson(steps.pulls.outputs.data).*.draft) }}'
          echo 'head.sha: ${{ toJson(fromJson(steps.pulls.outputs.data).*.head.sha) }}'
          echo 'reviewers: ${{ toJson(fromJson(steps.pulls.outputs.data).*.requested_reviewers) }}'
        if: github.event.state == 'success' && steps.pulls.outputs.status == 200
      
      # ブランチ保護
      - name: GET /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts
        uses: octokit/request-action@v2.0.2
        id: protection
        with:
          route: GET /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts
          owner: SnowCait
          repo: action-sandbox
          branch: ${{ toJson(fromJson(steps.pulls.outputs.data)[0].base.ref) }}
          mediaType: |
            previews:
              - groot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.state == 'success'
      - run: |
          echo 'contexts: ${{ toJson(fromJson(steps.pulls.outputs.data)) }}'
        if: github.event.state == 'success' && steps.pulls.outputs.status == 200

      # PR の最新コミットかつ reviewres が全員 Approve していたらコメントで通知する
      - name: POST /repos/{owner}/{repo}/commits/{sha}/comments
        uses: octokit/request-action@v2.0.2
        with:
          route: POST /repos/{owner}/{repo}/commits/{sha}/comments
          owner: SnowCait
          repo: action-sandbox
          sha: ${{ github.event.sha }}
          body: |
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.state == 'success'
