name: Unanimously Approved

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  unanimously-approved:
    runs-on: ubuntu-latest

    steps:
      - uses: snow-actions/unanimously-approved@unanimously-approved
