name: Wiki

on:
  gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          repository: SnowCait/action-sandbox.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2
      - run: git log -n 2
