name: Zip

on:
  push:
    paths: .github/workflows/zip.yml

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://hashicorp/packer:1.4.3

    steps:
      - run: apt-get install -y zip
      - run: zip --version
